version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app_prod
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/todo_app_prod
      SECRET_KEY_BASE: XHjD4qyUioNuHcA2gFQA96+U+BQywZLBKv9SDkXUoZlzo4u7e8FHLtQyFIwzJLyU
      PHX_SERVER: true
      MIX_ENV: prod
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db_data:
